### ISSUE TITLE
Coveralls dep is a smell

### ISSUE THREAD

**Issue by JoeCostanzo** [SEAPUNK/socketeer#77]
**Ran**: `npm test`
**Got**:
`socketeer/node_modules/coveralls/bin/coveralls.js:18
        throw err;
        ^
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}`
Seems to be a nagging issue for them. https://github.com/lemurheavy/coveralls-public/issues/487

**Solution**: Scrap the dep for another package out there instead, so the tests can be run smoothly?

**Comment by SEAPUNK** [comment]
coveralls runs fine, it "works" only when running on travis

if you want to run tests only without submitting coveralls info, use `npm run testonly`
